"""add average cost to inventory

Revision ID: 71b43ce224ae
Revises: aa553a55f74d
Create Date: 2026-10-09 14:51:48.795302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b43ce224ae'
down_revision: Union[str, Sequence[str], None] = 'aa553a55f74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('average_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'average_cost')
    # ### end Alembic commands ###
